-- ============================================================================
-- Migration 204: Provision the real admin role hierarchy (ADDITIVE / NO LOCKOUT)
-- Date: 2026-07-18
-- Author decision: owner, 2026-07-18
-- ============================================================================
--
-- WHY
-- ---
-- `lib/auth/admin.ts:134-140` — `hasPlatformAdminRole()` returns true for the
-- plain 'admin' role as well as 'platform_admin', making it identical to
-- `hasAdminRole()`. `verifyAdminScope()` short-circuits on it (:192-201), so the
-- `vertical_admins` membership check at :204-214 is UNREACHABLE for any 'admin'
-- user, and a vertical admin who requests another vertical is authorized for it.
-- The doc comment at :100-102 states the opposite intent, and the dead branch
-- proves it is a bug, not a design.
--
-- A prior session already tried to fix this: `api/admin/errors/route.ts:60-61`
-- switched to `hasPlatformAdminRole` with the comment "vertical admins should
-- NOT bypass scope". That fix has always been a no-op for the same reason.
--
-- THE TRAP THIS MIGRATION AVOIDS
-- -----------------------------
-- Production SQL (2026-07-18) showed NO platform admins exist. Both admin
-- accounts hold role='admin' with ZERO vertical_admins rows. Fixing the helper
-- FIRST would have locked both accounts — including the owner's — out of every
-- scope-checked route. The bug is currently load-bearing.
--
-- So the sequence is deliberately additive:
--   1. THIS MIGRATION grants the correct roles + memberships. Nothing is
--      removed; the existing (buggy) access path keeps working untouched, so
--      there is no window in which anyone loses access.
--   2. Owner tests admin surfaces on staging, then prod.
--   3. Re-run the verification queries below; confirm both accounts resolve as
--      platform admins THROUGH THE CORRECT PATH.
--   4. Only then, in a separate change, `hasPlatformAdminRole` is made strict
--      and the unscoped routes are audited.
--
-- INTENDED HIERARCHY (owner, 2026-07-18)
-- --------------------------------------
--   platform admin ⊃ vertical admin. Platform admins have everything vertical
--   admins have, plus cross-vertical reach. Vertical admins see ONLY their own
--   vertical. There is no blanket "admin" tier — the legacy 'admin' enum value
--   is how a vertical admin is represented in code.
--
--   tsjr00@gmail.com                → platform admin + CHIEF + vertical admin of every vertical
--   jennifer@8fifteenconsulting.com → platform admin (not chief) + vertical admin of every vertical
--
-- NOTES
-- -----
-- * Vertical rows are generated by SELECTing from `verticals` rather than
--   listing slugs, so no vertical can be silently missed (verification-
--   discipline Rule 4). Inactive verticals are included deliberately: an admin
--   should not lose reach because a vertical was paused.
-- * Idempotent — safe to re-run. Re-running repairs drift rather than erroring.
-- * TOLERANT of missing accounts: provisions whichever named accounts exist on
--   the target DB, NOTICEs the rest. Dev lacks the owner account (its only
--   tsjr00 row is a buyer test persona), so on Dev this provisions Jen alone
--   with no chief — expected. A post-condition aborts only if NEITHER named
--   account exists (a no-op run against the wrong database).
-- * `roles` is APPENDED to, never replaced, so no existing role is dropped.
-- * The `ensure_admin_premium_tier` trigger (mig 115) will fire on these role
--   writes and stamp buyer_tier='premium'. Expected and harmless.
--
-- ROLLBACK: see the block at the bottom of this file.
-- ============================================================================

BEGIN;

-- ── Pre-flight (TOLERANT): provision whichever named accounts exist; NOTICE
--    (do not abort) for any that are absent. The three write statements below
--    already filter `WHERE email IN (...)`, so a missing account simply no-ops.
--
--    WHY TOLERANT (2026-07-19): Dev is a seed environment that never had the
--    owner account — its only tsjr00 row is `marketgarden+tsjr00@gmail.com`, a
--    market-gardener BUYER test persona, not the admin. Staging + Prod hold both
--    real accounts. An all-or-nothing guard made this migration unrunnable on
--    Dev for a legitimate reason. The anti-lockout protection is preserved by a
--    POST-condition below, not a pre-condition here: the real danger is
--    provisioning NOBODY, which the post-check catches on every environment.
DO $$
DECLARE
  v_missing TEXT;
BEGIN
  SELECT string_agg(e, ', ') INTO v_missing
  FROM (VALUES ('tsjr00@gmail.com'), ('jennifer@8fifteenconsulting.com')) AS t(e)
  WHERE NOT EXISTS (
    SELECT 1 FROM user_profiles up WHERE up.email = t.e AND up.deleted_at IS NULL
  );

  IF v_missing IS NOT NULL THEN
    RAISE NOTICE 'Migration 204: named admin account(s) absent on this env, skipped: % (this is expected on Dev, where the owner account does not exist)', v_missing;
  END IF;
END $$;

-- ── 1. Platform admin role -------------------------------------------------
-- Sets the singular `role` column and APPENDS 'platform_admin' to the `roles`
-- array. Both columns are live and every check reads both (lib/auth/roles.ts:23),
-- so both must agree. Note tsjr00 currently has role='admin' but roles=['buyer'] —
-- the columns disagreed, and this reconciles them.
UPDATE user_profiles
SET
  role = 'platform_admin'::user_role,
  roles = CASE
            WHEN roles && ARRAY['platform_admin']::user_role[] THEN roles
            ELSE COALESCE(roles, ARRAY[]::user_role[]) || 'platform_admin'::user_role
          END,
  is_chief_platform_admin = (email = 'tsjr00@gmail.com'),
  updated_at = NOW()
WHERE email IN ('tsjr00@gmail.com', 'jennifer@8fifteenconsulting.com')
  AND deleted_at IS NULL;

-- ── 2. Profile vertical list ------------------------------------------------
-- `user_profiles.verticals` gates page access via enforceVerticalAccess()
-- (lib/auth/vertical-gate.ts). Both accounts were scoped to farmers_market only.
UPDATE user_profiles up
SET
  verticals = (SELECT ARRAY_AGG(v.vertical_id ORDER BY v.vertical_id) FROM verticals v),
  updated_at = NOW()
WHERE up.email IN ('tsjr00@gmail.com', 'jennifer@8fifteenconsulting.com')
  AND up.deleted_at IS NULL;

-- ── 3. vertical_admins membership, every vertical ---------------------------
-- This is the table `verifyAdminScope` consults once the helper is made strict.
-- Populating it now is what makes step 4 of the plan safe.
INSERT INTO vertical_admins (user_id, vertical_id, is_chief, granted_by)
SELECT
  up.user_id,
  v.vertical_id,
  (up.email = 'tsjr00@gmail.com') AS is_chief,
  (SELECT c.user_id FROM user_profiles c WHERE c.email = 'tsjr00@gmail.com' AND c.deleted_at IS NULL) AS granted_by
FROM user_profiles up
CROSS JOIN verticals v
WHERE up.email IN ('tsjr00@gmail.com', 'jennifer@8fifteenconsulting.com')
  AND up.deleted_at IS NULL
ON CONFLICT (user_id, vertical_id)
DO UPDATE SET is_chief = EXCLUDED.is_chief;

-- ── Post-condition (the real anti-lockout guard): at least one of the two
--    NAMED target accounts must now be a live platform admin. If BOTH were
--    absent, the three statements above no-oped and this migration provisioned
--    nobody — that is the dangerous "ran against the wrong database" case, so
--    abort and roll back. On Dev this passes because Jen is present; on
--    Staging/Prod it passes because both are.
DO $$
DECLARE
  v_provisioned INT;
BEGIN
  SELECT COUNT(*) INTO v_provisioned
  FROM user_profiles
  WHERE email IN ('tsjr00@gmail.com', 'jennifer@8fifteenconsulting.com')
    AND deleted_at IS NULL
    AND (role = 'platform_admin' OR roles && ARRAY['platform_admin']::user_role[]);

  IF v_provisioned = 0 THEN
    RAISE EXCEPTION 'Migration 204: provisioned NO platform admins — neither named account exists on this database. Refusing to commit a no-op admin migration (wrong environment?).';
  END IF;

  RAISE NOTICE 'Migration 204: % named account(s) now hold platform_admin.', v_provisioned;
END $$;

COMMIT;

NOTIFY pgrst, 'reload schema';

-- ============================================================================
-- VERIFICATION — run after applying. Expected results are stated inline.
-- ============================================================================

-- V1: named accounts present on THIS env are platform admins, chief flag set on
--     the owner only, each holds a vertical_admins row for every vertical.
--     EXPECT on Staging/Prod: 2 rows; role='platform_admin'; roles contains
--             platform_admin; is_chief_platform_admin true for tsjr00 only;
--             vertical_admin_count = (SELECT COUNT(*) FROM verticals) for both.
--     EXPECT on Dev: 1 row (Jen only — the owner account does not exist on Dev);
--             is_chief_platform_admin = false (no chief on Dev, expected).
-- SELECT up.email,
--        up.role::text                                   AS legacy_role,
--        up.roles::text[]                                AS roles_array,
--        up.is_chief_platform_admin,
--        up.verticals                                    AS profile_verticals,
--        (SELECT COUNT(*) FROM vertical_admins va WHERE va.user_id = up.user_id) AS vertical_admin_count,
--        (SELECT COUNT(*) FROM verticals)                AS total_verticals
-- FROM user_profiles up
-- WHERE up.email IN ('tsjr00@gmail.com','jennifer@8fifteenconsulting.com')
--   AND up.deleted_at IS NULL
-- ORDER BY up.is_chief_platform_admin DESC;

-- V2: THE LOCKOUT CHECK — accounts that would lose access when
--     hasPlatformAdminRole is made strict.
--     EXPECT: 0 rows. If this returns anything, DO NOT proceed to the
--     helper fix; provision those accounts first.
-- SELECT up.email, up.role::text, up.roles::text[]
-- FROM user_profiles up
-- WHERE up.deleted_at IS NULL
--   AND (up.role = 'admin' OR up.roles && ARRAY['admin']::user_role[])
--   AND NOT (up.role = 'platform_admin' OR up.roles && ARRAY['platform_admin']::user_role[])
--   AND NOT EXISTS (SELECT 1 FROM vertical_admins va WHERE va.user_id = up.user_id);

-- V3: chief platform admin state.
--     EXPECT on Staging/Prod: exactly 1 row, tsjr00@gmail.com.
--     EXPECT on Dev: 0 rows (owner absent → no chief; not an error on Dev).
-- SELECT email FROM user_profiles
-- WHERE is_chief_platform_admin = true AND deleted_at IS NULL;

-- ============================================================================
-- ROLLBACK — restores the pre-migration state exactly.
-- Both accounts return to role='admin', platform_admin removed from `roles`,
-- chief flag cleared, verticals scoped back to farmers_market, and the
-- vertical_admins rows removed. Access is NOT lost by rolling back, because
-- the buggy-but-load-bearing 'admin' path is still in place at that point.
-- ============================================================================
-- BEGIN;
-- DELETE FROM vertical_admins
-- WHERE user_id IN (SELECT user_id FROM user_profiles
--                   WHERE email IN ('tsjr00@gmail.com','jennifer@8fifteenconsulting.com'));
-- UPDATE user_profiles
-- SET role = 'admin'::user_role,
--     roles = ARRAY(SELECT unnest(roles) EXCEPT SELECT 'platform_admin'::user_role),
--     is_chief_platform_admin = false,
--     verticals = ARRAY['farmers_market']::text[],
--     updated_at = NOW()
-- WHERE email IN ('tsjr00@gmail.com','jennifer@8fifteenconsulting.com');
-- COMMIT;
-- NOTIFY pgrst, 'reload schema';
