-- ============================================================================
-- Migration 223: events sell on ACCEPTANCE, not on a vendor_market_schedules row
--                (T-36 — no attendee could order at any food-truck event)
-- ============================================================================
-- THE BUG (confirmed on staging 2026-08-10)
--
-- Adding any item at an FT event errored ERR_CART_003 "This pickup date is no
-- longer accepting orders." Nobody could pre-order at a food-truck event. The
-- owner hit it as an attendee AND as the event manager, because the fault is
-- per listing-and-market, not per user.
--
-- WHY: validate_cart_item_schedule delegates entirely to this function, and
-- this function keeps a listing only if it is private_pickup, OR an event in a
-- vertical OTHER than food_trucks, OR the vendor has an active
-- vendor_market_schedules row. FT events get no exemption, so they survived
-- only via a vms row — and api/vendor/events/[marketId]/respond NEVER creates
-- one. It writes market_vendors, event_vendor_listings and upserts
-- listing_markets; there is no vms write anywhere in that route.
--
-- Staging proof (market cc81fa25-997d-456b-9797-e50f8f4cdc30): vendor
-- response_status=accepted, market_type=event, vertical_id=food_trucks,
-- day_of_week=4 correctly matching the Thursday event date, schedule_active
-- =true, vms_id=NULL. Everything correct except the row that was never written.
--
-- WHY NOT "just create the vms row on acceptance"
--
-- That was considered and rejected. It would make "is this vendor attending?"
-- answerable from two places — market_vendors.response_status and the vms row —
-- with nothing keeping them in step. Miss the second on a cancellation and
-- ordering stays open for a truck that is not coming: a buyer pays for food
-- nobody will cook. Two records of one fact drifting apart is the exact failure
-- that has cost this codebase three separate incidents.
--
-- WHY NOT "exempt FT events like FM"
--
-- Also rejected, and this is the part worth remembering: the FM exemption
-- checks NOTHING about acceptance. It reads "event, and not food trucks". So on
-- FM today, a listing attached to an event market is orderable whether or not
-- the vendor ever accepted. Copying that to FT would have propagated the hole.
-- FM is deliberately left alone here — tightening it could switch off events
-- that work today, and that needs its own data check (backlog T-36).
--
-- THE CHANGE: migration 200 body VERBATIM + ONE added OR branch.
--
-- The file was generated by splicing into mig 200's actual text, not retyped.
--
-- SAFETY — why non-event listings cannot be affected:
--   * The change adds a DISJUNCT to an OR. Adding a disjunct can only ever ADD
--     rows; it can never remove one. No listing that sells today stops selling.
--   * The new disjunct requires m.market_type = 'event'. Traditional and
--     private_pickup listings cannot match it, in either vertical.
--   * FM events already match the branch above it, so their behaviour is
--     unchanged (an OR short-circuits to the same result).
--   * Therefore the ONLY rows that can newly appear are FT event listings whose
--     vendor has an ACCEPTED market_vendors row — which is precisely the set
--     that was broken.
--
-- Return shape unchanged → plain CREATE OR REPLACE, NO DROP (a DROP would break
-- the four wrapper functions). Grants: intentionally anon-executable for public
-- buyer browse (mig 149 allowlist); CREATE OR REPLACE keeps existing grants, so
-- no re-grant and no re-revoke are needed.
-- ============================================================================

-- ── PRE-CHECK — CAPTURE THIS BASELINE BEFORE APPLYING ──
--
-- Save the output. After applying, run it again and diff. Any listing whose
-- count CHANGED that is not an FT event listing means the reasoning above is
-- wrong and this migration should be rolled back.
--
--   SELECT l.id AS listing_id,
--          (SELECT count(*) FROM get_available_pickup_dates(l.id)) AS dates
--     FROM listings l
--    WHERE l.status = 'published' AND l.deleted_at IS NULL
--    ORDER BY 1;
--
-- And the specific listing that should CHANGE from 0 to >0:
--
--   SELECT count(*) FROM get_available_pickup_dates('<the FT event listing id>');
--   -- expect 0 before, >0 after

BEGIN;

CREATE OR REPLACE FUNCTION get_available_pickup_dates(
  p_listing_id UUID
)
RETURNS TABLE (
  market_id UUID,
  market_name TEXT,
  market_type TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  schedule_id UUID,
  day_of_week INTEGER,
  pickup_date DATE,
  start_time TIME,
  end_time TIME,
  cutoff_at TIMESTAMPTZ,
  is_accepting BOOLEAN,
  hours_until_cutoff NUMERIC,
  cutoff_hours INTEGER
) AS $$
BEGIN
  RETURN QUERY
  WITH listing_schedules AS (
    SELECT
      m.id as market_id,
      m.name as market_name,
      m.market_type,
      m.address,
      m.city,
      m.state,
      m.vertical_id,
      COALESCE(m.timezone, 'America/Chicago') as timezone,
      (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE as local_today,
      m.event_start_date,
      m.event_end_date,
      -- Cutoff logic with day-of event support (unchanged from migration 109)
      CASE
        -- FT parks: ALWAYS 0 (no advance cutoff)
        WHEN m.vertical_id = 'food_trucks' AND m.market_type != 'event' THEN 0
        -- Day-of event ordering: flag ON + event day arrived = accept until event ends
        WHEN m.market_type = 'event'
          AND m.event_allow_day_of_orders = true
          AND (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE >= m.event_start_date
        THEN 0
        -- All other markets: use DB cutoff_hours or vertical-specific default
        ELSE COALESCE(m.cutoff_hours,
          CASE
            WHEN m.market_type = 'event' THEN 24
            WHEN m.market_type = 'private_pickup' THEN 10
            ELSE 18
          END
        )
      END as cutoff_hours,
      ms.id as schedule_id,
      ms.day_of_week,
      COALESCE(vms.vendor_start_time, ms.start_time) as start_time,
      COALESCE(vms.vendor_end_time, ms.end_time) as end_time,
      vms.id as vms_id,
      COALESCE(l.advance_order_days, 0) as advance_order_days,
      -- T5 (mig 199): carried for the paid-park booking intersection below.
      l.vendor_profile_id as listing_vendor_id,
      m.park_mode
    FROM listing_markets lm
    JOIN listings l ON l.id = lm.listing_id
    JOIN markets m ON m.id = lm.market_id
      AND m.active = true
      AND (m.season_start IS NULL OR (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE >= m.season_start)
      AND (m.season_end IS NULL OR (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE <= m.season_end)
      AND (m.market_type != 'event' OR m.event_end_date >= (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE)
    JOIN market_schedules ms ON ms.market_id = m.id AND ms.active = true
    LEFT JOIN vendor_market_schedules vms
      ON vms.vendor_profile_id = l.vendor_profile_id
      AND vms.schedule_id = ms.id
      AND vms.is_active = true
    WHERE lm.listing_id = p_listing_id
      AND (
        -- Traditional markets in ALL verticals require an active vms row
        -- (vms.id IS NOT NULL after the is_active=true LEFT JOIN filter).
        m.market_type = 'private_pickup'
        OR (m.market_type = 'event' AND m.vertical_id != 'food_trucks')
        -- @paired-rule event-sells-on-acceptance (see apps/web/src/lib/paired-rules.ts)
        -- T-36 (mig 223): an event sells when the vendor has ACCEPTED the
        -- invitation. market_vendors.response_status is already the single
        -- record of event attendance, so this adds no second source of truth
        -- to drift. FT events previously had NO path here at all: the branch
        -- above exempts only non-FT, and api/vendor/events/[marketId]/respond
        -- never writes a vendor_market_schedules row — so every FT event
        -- errored ERR_CART_003 and nobody could order. Confirmed on staging
        -- 2026-08-10 (accepted vendor, correct day_of_week, active schedule,
        -- vms_id NULL).
        --
        -- Deliberately NOT scoped to food_trucks: an acceptance check is the
        -- correct rule for BOTH verticals. FM keeps its blanket exemption
        -- above for now (removing it could switch off FM events that work
        -- today), but this branch is what should survive if that is ever
        -- tightened. See backlog T-36.
        OR (m.market_type = 'event' AND EXISTS (
              SELECT 1 FROM market_vendors mv
               WHERE mv.market_id = m.id
                 AND mv.vendor_profile_id = l.vendor_profile_id
                 AND mv.response_status = 'accepted'
            ))
        OR vms.id IS NOT NULL
      )
  ),
  date_series AS (
    -- Regular markets: next 8 days
    SELECT DISTINCT (ls.local_today + i)::DATE as potential_date
    FROM listing_schedules ls
    CROSS JOIN generate_series(0, 7) as i

    UNION

    -- Events: include the actual event date range
    SELECT DISTINCT gs::DATE as potential_date
    FROM listing_schedules ls,
    LATERAL generate_series(
      ls.event_start_date,
      ls.event_end_date,
      '1 day'::interval
    ) as gs
    WHERE ls.market_type = 'event'
      AND ls.event_start_date IS NOT NULL
  ),
  matched_dates AS (
    SELECT
      ls.market_id,
      ls.market_name,
      ls.market_type,
      ls.address,
      ls.city,
      ls.state,
      ls.vertical_id,
      ls.timezone,
      ls.local_today,
      ls.cutoff_hours,
      ls.schedule_id,
      ls.day_of_week,
      ls.start_time,
      ls.end_time,
      ds.potential_date as pickup_date,
      ((ds.potential_date || ' ' || ls.start_time)::TIMESTAMP
        AT TIME ZONE ls.timezone) as pickup_start_utc,
      ((ds.potential_date || ' ' || ls.end_time)::TIMESTAMP
        AT TIME ZONE ls.timezone) as pickup_end_utc
    FROM listing_schedules ls
    CROSS JOIN date_series ds
    WHERE EXTRACT(DOW FROM ds.potential_date)::INTEGER = ls.day_of_week
      AND (
        ls.market_type != 'event'
        OR (ds.potential_date >= ls.event_start_date AND ds.potential_date <= ls.event_end_date)
      )
      AND (
        ls.vertical_id != 'food_trucks'
        OR ls.market_type = 'event'
        OR (ls.advance_order_days = 0 AND ds.potential_date = ls.local_today)
        OR (ls.advance_order_days > 0
            AND ds.potential_date >= ls.local_today + 2
            AND ds.potential_date <= ls.local_today + ls.advance_order_days)
      )
      -- PHASE C (mig 162): exclude dates the manager has cancelled for this market.
      AND NOT EXISTS (
        SELECT 1 FROM market_date_overrides o
        WHERE o.market_id = ls.market_id
          AND o.override_date = ds.potential_date
          AND o.status = 'cancelled'
      )
      -- T5 (mig 199): paid FT parks sell ONLY on PAID booking dates —
      -- booking = selling = paid (D1). Short-circuit order keeps FM, FT
      -- events, and free parks off the EXISTS entirely; only FT paid-park
      -- listings probe uq_park_spot_vendor_active (status='paid' implies the
      -- index's partial predicate). multiple_trucks grants NO exemption (D2).
      AND (
        ls.vertical_id != 'food_trucks'
        OR ls.market_type = 'event'
        OR ls.park_mode IS DISTINCT FROM 'paid'
        OR EXISTS (
          SELECT 1 FROM park_spot_bookings b
          WHERE b.vendor_profile_id = ls.listing_vendor_id
            AND b.market_id = ls.market_id
            AND b.booking_date = ds.potential_date
            AND b.status = 'paid'
            -- G1 (mig 200): a barred booking stays 'paid' (slot held, no
            -- resale) but must NOT sell — the truck was removed from this date.
            AND b.manager_barred_at IS NULL
        )
      )
  ),
  with_cutoff AS (
    SELECT
      md.*,
      CASE
        WHEN md.cutoff_hours = 0 THEN md.pickup_end_utc
        ELSE md.pickup_start_utc - (md.cutoff_hours || ' hours')::INTERVAL
      END as cutoff_at
    FROM matched_dates md
  )
  SELECT
    wc.market_id,
    wc.market_name,
    wc.market_type,
    wc.address,
    wc.city,
    wc.state,
    wc.schedule_id,
    wc.day_of_week,
    wc.pickup_date,
    wc.start_time,
    wc.end_time,
    wc.cutoff_at,
    (NOW() < wc.cutoff_at) as is_accepting,
    (EXTRACT(EPOCH FROM (wc.cutoff_at - NOW())) / 3600)::NUMERIC(10,2) as hours_until_cutoff,
    wc.cutoff_hours::INTEGER
  FROM with_cutoff wc
  WHERE wc.pickup_end_utc > NOW()
  ORDER BY wc.pickup_date, wc.start_time, wc.market_name;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION get_available_pickup_dates IS
  'Returns upcoming pickup dates for a listing. '
  'All date comparisons use market timezone (NOT UTC). '
  'Traditional markets (FM + FT): REQUIRE active vendor_market_schedules row. '
  'Events (both verticals): sell when the vendor has an ACCEPTED market_vendors row (mig 223). '
  'FM events additionally keep a blanket exemption. '
  'FM events: no vms requirement (organizer-driven). '
  'Private pickup: no vms requirement. '
  'FT non-event: today + advance_order_days window, 0 cutoff. '
  'Events: actual event date range as candidates. Past events auto-filtered. '
  'Day-of ordering: when event_allow_day_of_orders=true AND local_today >= event_start_date, cutoff=0 (accepting until event ends). '
  'Vendor custom times used when available. Enforces season dates. '
  'Phase C (mig 162): excludes dates with a market_date_overrides cancelled row. '
  'T5 (mig 199): park_mode=paid FT markets additionally require a PAID park_spot_bookings row for (vendor, market, date) — booking = selling = paid; multiple_trucks grants no exemption. '
  'G1 (mig 200): barred bookings (manager_barred_at set) do not sell — the bar keeps the row paid to hold the slot, but the truck was removed from that date.';

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ============================================================================
-- POST-APPLY VERIFICATION
-- ============================================================================
-- 1) The broken case now works:
--      SELECT pickup_date, is_accepting
--        FROM get_available_pickup_dates('<FT event listing id>');
--      -- expect the event date, is_accepting = true
--
-- 2) THE DIFFERENTIAL. Re-run the pre-check baseline and diff it. Expect
--    changes ONLY on FT event listings whose vendor accepted. A changed count
--    anywhere else = roll back.
--
-- 3) Acceptance is genuinely required — the hole this closes:
--      -- pick an FT event listing whose vendor has NOT accepted
--      SELECT count(*) FROM get_available_pickup_dates('<that listing id>');
--      -- expect 0
--
-- 4) Ordinary market ordering still works: pick one FM traditional listing and
--    one FT park listing and confirm their dates are unchanged from baseline.
--
-- ============================================================================
-- ROLLBACK — one statement, no data touched
-- ============================================================================
-- Re-apply migration 200 verbatim:
--   supabase/migrations/applied/20260718_200_pickup_dates_exclude_barred.sql
--
-- This migration is that file plus one OR branch, so re-applying it restores
-- the exact prior definition. CREATE OR REPLACE preserves grants; nothing is
-- dropped and no data is modified, so rollback is complete and instant.
-- ============================================================================
