-- ============================================================================
-- ⛔⛔⛔ SUPERSEDED BY MIG 234 (2026-08-16) — DO NOT APPLY THIS FILE ⛔⛔⛔
--
-- Owner decision 2026-08-16 ("go ahead and roll 225 into 234"): mig 234
-- (events_sell_on_attendance) contains this file's complete change (the T-39
-- exemption deletion) PLUS the Phase 4 attendance gate (bench exclusion +
-- fee paid/covered). Applying THIS file after 234 would REVERT the paid gate
-- while looking like a harmless catch-up — the exact silent-regression shape
-- mig 211 taught us about. This file was never applied to any environment;
-- it is kept only as 234's documented rollback target.
-- ============================================================================
-- Migration 225: FM events sell on ACCEPTANCE too — remove the blanket
--                farmers-market event exemption (T-39)
-- ============================================================================
-- THE HOLE
--
-- get_available_pickup_dates decided an event listing could sell via:
--
--     OR (m.market_type = 'event' AND m.vertical_id != 'food_trucks')
--
-- That branch checks NOTHING about the vendor. On farmers markets, a listing
-- attached to an event has been orderable whether the vendor accepted the
-- invitation, declined it, or was never invited at all. It reads as "an event,
-- and not food trucks" — a vertical test standing in for a permission test.
--
-- Migration 223 added the correct rule and deliberately scoped it to BOTH
-- verticals:
--
--     OR (m.market_type = 'event' AND EXISTS (
--           SELECT 1 FROM market_vendors mv
--            WHERE mv.market_id = m.id
--              AND mv.vendor_profile_id = l.vendor_profile_id
--              AND mv.response_status = 'accepted'))
--
-- so closing this hole is deleting the older line above it. Nothing is added.
--
-- ============================================================================
-- THE CHANGE — one line deleted, nothing else
-- ============================================================================
--
-- This file is migration 223's text with EXACTLY ONE LINE REMOVED (its line
-- 162, the exemption above), generated by splicing 223's actual file rather
-- than retyping it, and diffed to prove it: 349 lines vs 350, one deletion,
-- zero other executable changes. Two lines of the COMMENT block are corrected
-- because they asserted the exemption that no longer exists.
--
-- ============================================================================
-- SAFETY — read this, the risk runs the OPPOSITE way from mig 223
-- ============================================================================
--
-- Mig 223 ADDED a disjunct to an OR, which can only ever ADD rows: nothing
-- that sold could stop selling. **This migration REMOVES a disjunct, which can
-- only ever REMOVE rows.** An FM event listing that sells today will stop
-- selling unless it matches a surviving branch. That is the entire risk, and
-- it is why this needs a differential rather than a deploy.
--
-- PRE-REGISTERED PREDICTION (write down the pre-check output BEFORE applying):
--
--   * An FM EVENT listing keeps its pickup dates IF AND ONLY IF its vendor has
--     a market_vendors row with response_status = 'accepted' for that event —
--     or, independently, an active vendor_market_schedules row at it (the
--     `vms.id IS NOT NULL` branch is untouched and applies to every market
--     type).
--   * An FM event listing whose vendor never accepted goes from N dates to 0.
--     Those are the hole. Every one of them is a listing that could be ordered
--     from at an event the vendor has not agreed to attend.
--   * NOTHING ELSE MOVES. Traditional and private_pickup listings in both
--     verticals cannot match the deleted branch (it required
--     market_type='event'), and FT events never matched it (it required
--     vertical_id != 'food_trucks'). If the differential shows a change on any
--     non-FM-event listing, STOP and roll back — the prediction was wrong and
--     something else is going on.
--
-- ORDERING: this file contains migration 223's complete body, so it must be
-- applied AFTER 223 on any environment that already has it (Dev + Staging).
-- On Prod, where 223 is still pending, applying 223 then 225 in order keeps
-- the audit trail honest; applying 225 alone would also land 223's fix.
--
-- ============================================================================
-- PRE-CHECK — run BOTH, keep BOTH outputs
-- ============================================================================
--
-- (1) THE PREDICTION, per FM event listing. Rows with vendor_accepted = false
--     and dates_now > 0 are exactly the hole, and are exactly what should go
--     to zero. Rows with vendor_accepted = true must not move.
--
-- SELECT l.id AS listing_id, l.title, m.name AS event, m.event_start_date,
--        EXISTS (SELECT 1 FROM market_vendors mv
--                 WHERE mv.market_id = m.id
--                   AND mv.vendor_profile_id = l.vendor_profile_id
--                   AND mv.response_status = 'accepted') AS vendor_accepted,
--        (SELECT count(*) FROM get_available_pickup_dates(l.id) d
--          WHERE d.market_id = m.id) AS dates_now
--   FROM listings l
--   JOIN listing_markets lm ON lm.listing_id = l.id
--   JOIN markets m          ON m.id = lm.market_id
--  WHERE l.status = 'published' AND l.deleted_at IS NULL
--    AND m.market_type = 'event'
--    AND m.vertical_id = 'farmers_market'
--  ORDER BY vendor_accepted, m.name, l.title;
--
-- (2) THE CONTROL — a per-listing date count across EVERY published listing.
--     Re-run it after applying and diff the two outputs. Only listings named
--     in (1) with vendor_accepted = false may differ. This is the same
--     baseline method mig 223 used, and it is what caught that fix's blast
--     radius exactly.
--
-- SELECT l.id, count(d.*) AS date_count
--   FROM listings l
--   LEFT JOIN LATERAL get_available_pickup_dates(l.id) d ON true
--  WHERE l.status = 'published' AND l.deleted_at IS NULL
--  GROUP BY l.id
--  ORDER BY l.id;
--
-- ============================================================================
-- POST-CHECK
-- ============================================================================
--
-- (a) Re-run pre-check (1). Every vendor_accepted = false row must now read 0.
--     Every vendor_accepted = true row must be unchanged.
-- (b) Re-run pre-check (2) and diff against the baseline. Any listing that
--     moved and is NOT an unaccepted FM event listing is a failure — roll back.
-- (c) Browser: an FM event the vendor accepted still takes orders.
--
-- ROLLBACK: re-apply supabase/migrations/20260810_223_events_sell_on_acceptance.sql
-- verbatim. One statement, no data touched, restores the exemption exactly.
--
-- ============================================================================
-- WHY A VERTICAL TEST WAS NEVER A PERMISSION TEST
-- ============================================================================
--
-- `vertical_id != 'food_trucks'` answered "which product is this?" and was
-- used to decide "is this vendor allowed to sell here?". Those are different
-- questions, and the line survived nineteen rewrites of this function because
-- each rewrite copied the body forward verbatim — the correct thing to do for
-- safety, and the reason a wrong branch can live for months. Mig 223 wrote its
-- replacement to be vertical-agnostic on purpose so that closing this would be
-- a deletion rather than a redesign. See backlog T-39, and mig 223's header
-- for why exempting FT to match FM was rejected as the fix.

CREATE OR REPLACE FUNCTION get_available_pickup_dates(
  p_listing_id UUID
)
RETURNS TABLE (
  market_id UUID,
  market_name TEXT,
  market_type TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  schedule_id UUID,
  day_of_week INTEGER,
  pickup_date DATE,
  start_time TIME,
  end_time TIME,
  cutoff_at TIMESTAMPTZ,
  is_accepting BOOLEAN,
  hours_until_cutoff NUMERIC,
  cutoff_hours INTEGER
) AS $$
BEGIN
  RETURN QUERY
  WITH listing_schedules AS (
    SELECT
      m.id as market_id,
      m.name as market_name,
      m.market_type,
      m.address,
      m.city,
      m.state,
      m.vertical_id,
      COALESCE(m.timezone, 'America/Chicago') as timezone,
      (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE as local_today,
      m.event_start_date,
      m.event_end_date,
      -- Cutoff logic with day-of event support (unchanged from migration 109)
      CASE
        -- FT parks: ALWAYS 0 (no advance cutoff)
        WHEN m.vertical_id = 'food_trucks' AND m.market_type != 'event' THEN 0
        -- Day-of event ordering: flag ON + event day arrived = accept until event ends
        WHEN m.market_type = 'event'
          AND m.event_allow_day_of_orders = true
          AND (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE >= m.event_start_date
        THEN 0
        -- All other markets: use DB cutoff_hours or vertical-specific default
        ELSE COALESCE(m.cutoff_hours,
          CASE
            WHEN m.market_type = 'event' THEN 24
            WHEN m.market_type = 'private_pickup' THEN 10
            ELSE 18
          END
        )
      END as cutoff_hours,
      ms.id as schedule_id,
      ms.day_of_week,
      COALESCE(vms.vendor_start_time, ms.start_time) as start_time,
      COALESCE(vms.vendor_end_time, ms.end_time) as end_time,
      vms.id as vms_id,
      COALESCE(l.advance_order_days, 0) as advance_order_days,
      -- T5 (mig 199): carried for the paid-park booking intersection below.
      l.vendor_profile_id as listing_vendor_id,
      m.park_mode
    FROM listing_markets lm
    JOIN listings l ON l.id = lm.listing_id
    JOIN markets m ON m.id = lm.market_id
      AND m.active = true
      AND (m.season_start IS NULL OR (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE >= m.season_start)
      AND (m.season_end IS NULL OR (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE <= m.season_end)
      AND (m.market_type != 'event' OR m.event_end_date >= (NOW() AT TIME ZONE COALESCE(m.timezone, 'America/Chicago'))::DATE)
    JOIN market_schedules ms ON ms.market_id = m.id AND ms.active = true
    LEFT JOIN vendor_market_schedules vms
      ON vms.vendor_profile_id = l.vendor_profile_id
      AND vms.schedule_id = ms.id
      AND vms.is_active = true
    WHERE lm.listing_id = p_listing_id
      AND (
        -- Traditional markets in ALL verticals require an active vms row
        -- (vms.id IS NOT NULL after the is_active=true LEFT JOIN filter).
        m.market_type = 'private_pickup'
        -- T-36 (mig 223): an event sells when the vendor has ACCEPTED the
        -- invitation. market_vendors.response_status is already the single
        -- record of event attendance, so this adds no second source of truth
        -- to drift. FT events previously had NO path here at all: the branch
        -- above exempts only non-FT, and api/vendor/events/[marketId]/respond
        -- never writes a vendor_market_schedules row — so every FT event
        -- errored ERR_CART_003 and nobody could order. Confirmed on staging
        -- 2026-08-10 (accepted vendor, correct day_of_week, active schedule,
        -- vms_id NULL).
        --
        -- Deliberately NOT scoped to food_trucks: an acceptance check is the
        -- correct rule for BOTH verticals.
        --
        -- T-39 (mig 225): the FM blanket exemption that used to sit ABOVE this
        -- branch — `OR (market_type = 'event' AND vertical_id != 'food_trucks')`
        -- — is DELETED. It checked nothing about the vendor, so on farmers
        -- markets a listing attached to an event was orderable whether the
        -- vendor accepted, declined, or was never invited. A vertical test was
        -- standing in for a permission test. This branch is now the ONLY way an
        -- event sells, in either vertical.
        --
        -- ⛔ DO NOT RE-ADD A VERTICAL EXEMPTION HERE. If FM events ever need to
        -- sell without an acceptance, that is a decision about what acceptance
        -- MEANS on FM — make it explicit and name it, do not reintroduce a
        -- `vertical_id != …` shortcut. Guarded by flow-integrity.test.ts.
        OR (m.market_type = 'event' AND EXISTS (
              SELECT 1 FROM market_vendors mv
               WHERE mv.market_id = m.id
                 AND mv.vendor_profile_id = l.vendor_profile_id
                 AND mv.response_status = 'accepted'
            ))
        OR vms.id IS NOT NULL
      )
  ),
  date_series AS (
    -- Regular markets: next 8 days
    SELECT DISTINCT (ls.local_today + i)::DATE as potential_date
    FROM listing_schedules ls
    CROSS JOIN generate_series(0, 7) as i

    UNION

    -- Events: include the actual event date range
    SELECT DISTINCT gs::DATE as potential_date
    FROM listing_schedules ls,
    LATERAL generate_series(
      ls.event_start_date,
      ls.event_end_date,
      '1 day'::interval
    ) as gs
    WHERE ls.market_type = 'event'
      AND ls.event_start_date IS NOT NULL
  ),
  matched_dates AS (
    SELECT
      ls.market_id,
      ls.market_name,
      ls.market_type,
      ls.address,
      ls.city,
      ls.state,
      ls.vertical_id,
      ls.timezone,
      ls.local_today,
      ls.cutoff_hours,
      ls.schedule_id,
      ls.day_of_week,
      ls.start_time,
      ls.end_time,
      ds.potential_date as pickup_date,
      ((ds.potential_date || ' ' || ls.start_time)::TIMESTAMP
        AT TIME ZONE ls.timezone) as pickup_start_utc,
      ((ds.potential_date || ' ' || ls.end_time)::TIMESTAMP
        AT TIME ZONE ls.timezone) as pickup_end_utc
    FROM listing_schedules ls
    CROSS JOIN date_series ds
    WHERE EXTRACT(DOW FROM ds.potential_date)::INTEGER = ls.day_of_week
      AND (
        ls.market_type != 'event'
        OR (ds.potential_date >= ls.event_start_date AND ds.potential_date <= ls.event_end_date)
      )
      AND (
        ls.vertical_id != 'food_trucks'
        OR ls.market_type = 'event'
        OR (ls.advance_order_days = 0 AND ds.potential_date = ls.local_today)
        OR (ls.advance_order_days > 0
            AND ds.potential_date >= ls.local_today + 2
            AND ds.potential_date <= ls.local_today + ls.advance_order_days)
      )
      -- PHASE C (mig 162): exclude dates the manager has cancelled for this market.
      AND NOT EXISTS (
        SELECT 1 FROM market_date_overrides o
        WHERE o.market_id = ls.market_id
          AND o.override_date = ds.potential_date
          AND o.status = 'cancelled'
      )
      -- T5 (mig 199): paid FT parks sell ONLY on PAID booking dates —
      -- booking = selling = paid (D1). Short-circuit order keeps FM, FT
      -- events, and free parks off the EXISTS entirely; only FT paid-park
      -- listings probe uq_park_spot_vendor_active (status='paid' implies the
      -- index's partial predicate). multiple_trucks grants NO exemption (D2).
      AND (
        ls.vertical_id != 'food_trucks'
        OR ls.market_type = 'event'
        OR ls.park_mode IS DISTINCT FROM 'paid'
        OR EXISTS (
          SELECT 1 FROM park_spot_bookings b
          WHERE b.vendor_profile_id = ls.listing_vendor_id
            AND b.market_id = ls.market_id
            AND b.booking_date = ds.potential_date
            AND b.status = 'paid'
            -- G1 (mig 200): a barred booking stays 'paid' (slot held, no
            -- resale) but must NOT sell — the truck was removed from this date.
            AND b.manager_barred_at IS NULL
        )
      )
  ),
  with_cutoff AS (
    SELECT
      md.*,
      CASE
        WHEN md.cutoff_hours = 0 THEN md.pickup_end_utc
        ELSE md.pickup_start_utc - (md.cutoff_hours || ' hours')::INTERVAL
      END as cutoff_at
    FROM matched_dates md
  )
  SELECT
    wc.market_id,
    wc.market_name,
    wc.market_type,
    wc.address,
    wc.city,
    wc.state,
    wc.schedule_id,
    wc.day_of_week,
    wc.pickup_date,
    wc.start_time,
    wc.end_time,
    wc.cutoff_at,
    (NOW() < wc.cutoff_at) as is_accepting,
    (EXTRACT(EPOCH FROM (wc.cutoff_at - NOW())) / 3600)::NUMERIC(10,2) as hours_until_cutoff,
    wc.cutoff_hours::INTEGER
  FROM with_cutoff wc
  WHERE wc.pickup_end_utc > NOW()
  ORDER BY wc.pickup_date, wc.start_time, wc.market_name;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION get_available_pickup_dates IS
  'Returns upcoming pickup dates for a listing. '
  'All date comparisons use market timezone (NOT UTC). '
  'Traditional markets (FM + FT): REQUIRE active vendor_market_schedules row. '
  'Events (both verticals): sell ONLY when the vendor has an ACCEPTED market_vendors row (mig 223 + mig 225). '
  'FM events have NO blanket exemption — removed by mig 225 (T-39). Acceptance is required in both verticals. '
  'Events do not require a vendor_market_schedules row; acceptance replaces it. '
  'Private pickup: no vms requirement. '
  'FT non-event: today + advance_order_days window, 0 cutoff. '
  'Events: actual event date range as candidates. Past events auto-filtered. '
  'Day-of ordering: when event_allow_day_of_orders=true AND local_today >= event_start_date, cutoff=0 (accepting until event ends). '
  'Vendor custom times used when available. Enforces season dates. '
  'Phase C (mig 162): excludes dates with a market_date_overrides cancelled row. '
  'T5 (mig 199): park_mode=paid FT markets additionally require a PAID park_spot_bookings row for (vendor, market, date) — booking = selling = paid; multiple_trucks grants no exemption. '
  'G1 (mig 200): barred bookings (manager_barred_at set) do not sell — the bar keeps the row paid to hold the slot, but the truck was removed from that date.';

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ============================================================================
-- POST-APPLY VERIFICATION (mig 225 — supersedes 223's block, which was about
-- the opposite direction of change)
-- ============================================================================
-- 1) THE HOLE IS CLOSED. Take an FM event listing whose vendor has NOT
--    accepted (pre-check (1), vendor_accepted = false):
--      SELECT count(*) FROM get_available_pickup_dates('<that listing id>');
--      -- expect 0.  Before this migration it returned dates.
--
-- 2) ACCEPTED FM EVENTS STILL SELL. Take an FM event listing whose vendor HAS
--    accepted:
--      SELECT pickup_date, is_accepting
--        FROM get_available_pickup_dates('<that listing id>');
--      -- expect the event dates, unchanged from the pre-check count.
--
-- 3) THE DIFFERENTIAL — the one that matters. Re-run pre-check (2) and diff it
--    against the baseline. The ONLY listings whose count may change are FM
--    event listings with vendor_accepted = false, and they must go to 0. A
--    changed count on ANY traditional, private-pickup, or FT listing means the
--    prediction was wrong: ROLL BACK and re-diagnose. Do not reason past it.
--
-- 4) Browser: an attendee can still order at an FM event whose vendor accepted.
--
-- ============================================================================
-- ROLLBACK — one statement, no data touched
-- ============================================================================
-- Re-apply migration 223 verbatim:
--   supabase/migrations/20260810_223_events_sell_on_acceptance.sql
--
-- This migration is that file with exactly one line deleted, so re-applying it
-- restores the exact prior definition including the FM exemption. CREATE OR
-- REPLACE preserves grants; nothing is dropped and no data is modified, so
-- rollback is complete and instant.
--
-- ⚠ If 225 is applied to Prod WITHOUT 223 having been applied first, rolling
-- back to 223 still leaves T-36 fixed (FT events sell on acceptance) — 223 is
-- the correct fallback in every environment.
-- ============================================================================
