-- Migration 148: market_documents — manager-uploaded verification docs
--
-- =============================================================================
-- ROLLBACK
-- =============================================================================
-- To revert this migration on any environment, run as a single transaction:
--
--   BEGIN;
--     DROP TABLE IF EXISTS market_documents CASCADE;
--     DELETE FROM storage.objects WHERE bucket_id = 'market-documents';
--     DELETE FROM storage.buckets WHERE id = 'market-documents';
--   COMMIT;
--   NOTIFY pgrst, 'reload schema';
--
-- Risk profile:
--   PRE-application or DEV-only: zero data loss; safe.
--   POST-application on Staging/Prod with managers having uploaded docs:
--     ROLLBACK DELETES ALL UPLOADED FILES from both the table AND the
--     bucket. Files in Supabase Storage are unrecoverable after the
--     bucket delete. Coordinate with the user before running on Prod.
--
-- Dependencies:
--   - mig 001 (markets, auth.users)
--   - Storage admin (creating storage.buckets row + policies — Supabase
--     storage tables exist by default).
-- =============================================================================
--
-- What this migration does:
--
-- 1. Creates `market_documents` table — one row per uploaded file. Manager
--    of a market uploads verification docs (LLC filing, COI, venue proof,
--    etc.). Admin downloads to review during the approval workflow.
--
--    Document types (manager picks from dropdown on upload):
--      - 'legal_entity_filing'  — LLC docs / state biz reg / city permit
--      - 'owners_managers_list' — names + contact info of other principals
--      - 'market_website'       — screenshot or URL of website
--      - 'insurance_coi'        — Certificate of Insurance
--      - 'venue_proof'          — lease, recent vendor permit, photo proof
--      - 'other'                — catch-all; manager labels via notes field
--
--    No per-doc review state in v1 (admin downloads + makes the
--    market-status approval call as a whole — see Bug 6 / mig 133 intake
--    workflow). Future: add review_status + reviewer_user_id + notes
--    columns if per-doc audit trail becomes useful.
--
-- 2. Creates `market-documents` Supabase Storage bucket — PRIVATE (no
--    public reads). Manager + admin access via short-lived signed URLs
--    generated by the documents API routes. RLS policies on
--    storage.objects scope manager INSERT/DELETE to their own markets;
--    SELECT goes through the service-client + signed-URL path.
--
-- 3. RLS on market_documents: default-deny (matches mig 137 / mig 147
--    pattern). All access via API routes using service client; routes
--    enforce manager OR admin auth before touching the table.

-- ----------------------------------------------------------------------------
-- 1. market_documents table
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS market_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  market_id UUID NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
  uploader_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,

  document_type TEXT NOT NULL CHECK (document_type IN (
    'legal_entity_filing',
    'owners_managers_list',
    'market_website',
    'insurance_coi',
    'venue_proof',
    'other'
  )),

  -- Storage object path (within the market-documents bucket).
  -- Format: <market_id>/<uuid>-<original-filename>
  storage_path TEXT NOT NULL,

  -- Display metadata
  file_name TEXT NOT NULL,
  file_size_bytes INTEGER NOT NULL CHECK (file_size_bytes > 0),
  mime_type TEXT NOT NULL,

  -- Optional free-text label (esp. useful when document_type='other').
  notes TEXT,

  -- Audit
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE market_documents IS
  'Mig 148: manager-uploaded verification documents for a market. Admin reviews during the status=pending → active approval workflow (Bug 6). Files live in the market-documents Supabase Storage bucket (private; signed URLs only).';

COMMENT ON COLUMN market_documents.uploader_user_id IS
  'auth.users.id of the manager who uploaded. RESTRICT delete so we keep the audit trail even if the user account is removed (rare; admin tools can re-attribute if needed).';

COMMENT ON COLUMN market_documents.storage_path IS
  'Path within the market-documents bucket. Format: <market_id>/<uuid>-<filename>. Used by the API routes to generate signed download URLs.';

-- ----------------------------------------------------------------------------
-- 2. Indexes
-- ----------------------------------------------------------------------------

-- Manager + admin "list docs for this market" — primary access pattern
CREATE INDEX IF NOT EXISTS idx_market_documents_market
  ON market_documents (market_id, uploaded_at DESC);

-- "Find all docs uploaded by this user" — uncommon, but keeps audit
-- queries cheap if the admin tools ever need it.
CREATE INDEX IF NOT EXISTS idx_market_documents_uploader
  ON market_documents (uploader_user_id);

-- ----------------------------------------------------------------------------
-- 3. RLS — default-deny, service client only (matches mig 137 / mig 147)
-- ----------------------------------------------------------------------------

ALTER TABLE market_documents ENABLE ROW LEVEL SECURITY;

-- No policies — service_role only. All reads/writes via API routes that
-- enforce auth (isMarketManager for managers; admin role check for admins).

-- ----------------------------------------------------------------------------
-- 4. Storage bucket — market-documents (PRIVATE)
-- ----------------------------------------------------------------------------
--
-- INSERT into storage.buckets registers the bucket. `public = false` means
-- no anonymous reads — all access goes through signed URLs the API routes
-- generate (~1hr TTL) for admin previews / downloads.
--
-- ON CONFLICT DO NOTHING so re-running this migration is idempotent.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'market-documents',
  'market-documents',
  false,                            -- private bucket; no public URLs
  3145728,                          -- 3 MB per file (matches platform-wide cap)
  ARRAY[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 5. Storage object RLS policies
-- ----------------------------------------------------------------------------
--
-- Default Supabase storage RLS denies everything except service_role.
-- We're keeping that default — the API routes use service_client for ALL
-- storage operations (upload, generate signed URL, delete). No direct
-- client-side storage access. This matches how the vendor-images bucket
-- is treated for the manager logo upload (logo/route.ts uses createClient
-- for the upload but the bucket already permits authenticated users via
-- its own policies; market-documents is stricter — service-only — because
-- the contents are legal/identity documents).

-- ----------------------------------------------------------------------------
-- Schema cache reload
-- ----------------------------------------------------------------------------

NOTIFY pgrst, 'reload schema';
